# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 27fa5edca556e8717de08e82a65057b90dd2479b4fc068b13f2369ee34175161b6089120a15609760de8a308c5d80b4181bb563201d52bea4955b64ea9e556a2

test:
  secret_key_base: 53805d5d0295cde801fdc9607f4f4238c10cb4b4a2b66a5c153fe4af8b2d3a5303e5c809ba4916cb7427741b72cd4f75109d40753860dd57185905bb5390178d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
